### ISSUE TITLE
Fatal Error on Startup

### ISSUE THREAD

**Issue by MichaelKhalil** [lukylunatics/videoReference#1]
Hello!

I've been running into an issue trying to boot up Maya after attempting to install the this module. I have attempted installing both using the dragDropInstall.py and manually adding the VideoReference folder and videoReference.mod.

This occurs after restarting Maya 2022 after installation in the splash screen. I am currently using Python 3.7-64, and have also attempted with Python 3.10-64.

My computer specs are:
CPU: Ryzen 7 2700x
Ram: 2x 16GB G.Skill 3200
GPU: Nvidia RTX 3080ti
Motherboard: X370 SLI Plus

I have attempted some fixes online regarding modules such as changing the rendering engine, starting as Administrator, and adding OPENSSL_ia32cap=~0x200000200000000 to user variables. Removing the folder and .mod file from the modules folder will allow me to reopen Maya. 

Managing video reference is a struggle for animation, so I'd love to use this plugin! Please let me know if there's any logs I could provide which could help.

Thanks!

![image](https://user-images.githubusercontent.com/18673871/179148598-f242b58c-8dcd-4da4-8e1e-ba162eec8431.png)

**Comment by lukylunatics** [comment]
> Hello!
> 
> I've been running into an issue trying to boot up Maya after attempting to install the this module. I have attempted installing both using the dragDropInstall.py and manually adding the VideoReference folder and videoReference.mod.
> 
> This occurs after restarting Maya 2022 after installation in the splash screen. I am currently using Python 3.7-64, and have also attempted with Python 3.10-64.
> 
> My computer specs are: CPU: Ryzen 7 2700x Ram: 2x 16GB G.Skill 3200 GPU: Nvidia RTX 3080ti Motherboard: X370 SLI Plus
> 
> I have attempted some fixes online regarding modules such as changing the rendering engine, starting as Administrator, and adding OPENSSL_ia32cap=~0x200000200000000 to user variables. Removing the folder and .mod file from the modules folder will allow me to reopen Maya.
> 
> Managing video reference is a struggle for animation, so I'd love to use this plugin! Please let me know if there's any logs I could provide which could help.
> 
> Thanks!
> 
> ![image](https://user-images.githubusercontent.com/18673871/179148598-f242b58c-8dcd-4da4-8e1e-ba162eec8431.png)

Hi, is it possible to use 2023 for now as a quick workaround? Autodesk changed a few thing with the python package manager from 22 to 23. I'll try to address this weekend maybe.

**Comment by MichaelKhalil** [comment]
Thank for the suggestion, I didn't think to try 2023! 

Currently trying to use the dragDropInstall.py unzipped to a folder in Downloads, I'm receiving this error in the log preventing the installation:

    import maya.app.general.executeDroppedPythonFile as myTempEDPF
    myTempEDPF.executeDroppedPythonFile("C:/Users/Michael/Downloads/videoReference-main/dragDropInstall.py", "")
    del myTempEDPF
    Error: KeyError: file C:\Program Files/Autodesk/Maya2023\Python\lib\os.py line 679: 'MAYA_PYTHON_VERSION'

I've made sure that I don't have Python 2 installed if that'd cause a conflict. Loading the files in manually, It doesn't appear to surface in the Create dropdown. I am able to load into this version of Maya, here's the log attached.
[log.txt](https://github.com/lukylunatics/videoReference/files/9125114/log.txt)
 
![image](https://user-images.githubusercontent.com/18673871/179338092-38fcbf34-3f1b-4014-8abc-254b4f54b5fa.png)

**Comment by lukylunatics** [comment]
> Thank for the suggestion, I didn't think to try 2023!
> 
> Currently trying to use the dragDropInstall.py unzipped to a folder in Downloads, I'm receiving this error in the log preventing the installation:
> 
> ```
> import maya.app.general.executeDroppedPythonFile as myTempEDPF
> myTempEDPF.executeDroppedPythonFile("C:/Users/Michael/Downloads/videoReference-main/dragDropInstall.py", "")
> del myTempEDPF
> Error: KeyError: file C:\Program Files/Autodesk/Maya2023\Python\lib\os.py line 679: 'MAYA_PYTHON_VERSION'
> ```
> 
> I've made sure that I don't have Python 2 installed if that'd cause a conflict. Loading the files in manually, It doesn't appear to surface in the Create dropdown. I am able to load into this version of Maya, here's the log attached. [log.txt](https://github.com/lukylunatics/videoReference/files/9125114/log.txt)
> 
> ![image](https://user-images.githubusercontent.com/18673871/179338092-38fcbf34-3f1b-4014-8abc-254b4f54b5fa.png)

Ok this release has a pretty old installer - let me fix this today.

**Comment by lukylunatics** [comment]
@MichaelKhalil could you please check if this works for You?
[videoReference_v.1.0.2.zip](https://github.com/lukylunatics/videoReference/files/9125583/videoReference_v.1.0.2.zip)
![videoReference_issue](https://user-images.githubusercontent.com/71616016/179351533-c5b3b474-03b6-44e7-86f5-05bb1e369275.png)
Support for 2022 will be more tricky since:
https://knowledge.autodesk.com/support/maya/learn-explore/caas/CloudHelp/cloudhelp/2023/ENU/Maya-WhatsNewPR/files/GUID-DF43840B-4DB1-43F8-BFD1-97D8D031B91D-htm.html

`Maya uses Python version 3.9. If you have plug-ins or scripts written in Python 3.7, you may encounter issues when porting them to Python 3.9 as code compatibility is not guaranteed between these two versions. Consult [What's New in Python 3.8](https://docs.python.org/3/whatsnew/3.8.html) and [What's New in Python 3.9](https://docs.python.org/3/whatsnew/3.9.html) for details.

Maya no longer supports Python2, and can no longer be started in Python 2 mode.
`

Also you do not need python standalone for this. It uses mayapy - the one that comes with maya preinstalled. I think the crash on 2022 was related to pip not being able to find a matching package for python 3.7 since it is already quite old. 

The menu item under create should be working though.

Dependencies are now being installed in the modules script folder so you can easily remove them with the whole module.

**Comment by lukylunatics** [comment]
Please check the lates v.1.0.2 release:
[https://github.com/lukylunatics/videoReference/releases/tag/v.1.0.2](url)
